---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./networkpolicy.yaml
  # Flux-Kustomizations
  # - ./esphome/ks.yaml
  - ./frigate/ks.yaml
  # - ./home-assistant/ks.yaml
  - ./mqtt/ks.yaml
  # - ./music-assistant/ks.yaml
  # - ./scrypted/ks.yaml
  - ./zigbee2mqtt/ks.yaml
