---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  interval: 30m
  url: https://zebernst.github.io/synology-csi-talos
  timeout: 3m
